In [2]:


import matplotlib.pyplot as plt
import numpy as np
import sys
import os
import subprocess
import math
import pandas as pd

In [69]:

def convert(list, end): 
      
    # multiply each integer element with its  
    # corresponding power and perform summation 
  
    res = sum(d * 10**(end-i) for i, d in enumerate(list[0:end])) 
      
    return(int(res/10))



In [72]:
x = 0

while x != 9:
    x = 0
    Array = np.arange(1,10,1)
    np.random.shuffle(Array)
    print(Array)
    for i in range(1,10,1):
        Number = convert(Array,i)
        if Number % i == 0:
            x+=1
        
    
print(Number)

[4 1 6 5 2 3 7 8 9]
[4 7 2 3 5 1 9 8 6]
[2 5 3 6 9 8 1 7 4]
[2 9 7 3 4 5 1 8 6]
[7 9 3 4 1 5 6 2 8]
[2 4 5 7 1 9 6 3 8]
[9 4 7 8 1 3 2 5 6]
[3 5 6 2 9 7 4 8 1]
[7 6 3 8 2 5 1 9 4]
[1 7 5 6 3 4 9 8 2]
[2 7 4 3 8 5 6 9 1]
[1 4 3 8 7 6 9 2 5]
[3 8 1 9 6 4 7 5 2]
[9 7 6 2 4 5 8 3 1]
[8 2 1 9 7 6 3 5 4]
[8 6 2 3 5 9 4 7 1]
[4 9 7 6 5 1 2 8 3]
[1 6 2 3 5 7 4 8 9]
[7 3 4 9 8 6 2 5 1]
[6 8 1 7 3 5 2 4 9]
[7 9 4 3 2 6 5 1 8]
[5 3 8 2 7 1 9 6 4]
[3 4 2 9 7 6 1 5 8]
[2 6 3 7 9 5 8 4 1]
[9 7 3 6 8 1 2 5 4]
[4 1 7 8 9 6 3 2 5]
[5 8 6 3 7 2 9 1 4]
[2 8 4 1 3 5 9 6 7]
[7 4 5 9 6 2 1 3 8]
[1 5 3 2 7 9 8 6 4]
[9 2 8 4 7 3 5 1 6]
[2 7 1 6 9 8 3 5 4]
[1 3 4 7 5 8 2 9 6]
[4 2 7 5 6 1 8 3 9]
[8 1 4 6 3 7 9 5 2]
[2 4 9 8 3 5 1 6 7]
[6 3 2 5 7 8 9 4 1]
[3 7 6 8 1 5 4 2 9]
[1 8 2 9 3 4 7 6 5]
[8 1 7 6 5 3 9 4 2]
[3 1 6 5 2 9 7 4 8]
[2 4 3 6 1 7 8 9 5]
[8 6 9 4 1 3 2 5 7]
[4 3 1 5 6 2 8 9 7]
[8 2 3 6 1 4 9 5 7]
[7 9 2 4 8 6 3 5 1]
[7 4 5 3 2 6 9 1 8]
[7 6 9 4 5 1 8 2 3]
[7 8 9 2 3 4 1 6 5]
[6 4 5 1 3 9 8 7 2]


KeyboardInterrupt: 

In [66]:
    Array = np.arange(1,10,1)
    print(np.random.shuffle(Array))
    print(Array)

None
[3 7 1 9 2 5 6 4 8]


In [70]:
print(9*10)


90


In [71]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
